name: medical_calculator
description: Dart package for medical equation calculation
version: 1.0.0
repository: https://github.com/devsdocs/medical_calculator

environment:
  sdk: ^3.1.1

dependencies:
  reusable_tools: ^1.0.13
  super_measurement: ^1.0.4

dev_dependencies:
  lint: ^2.1.2
  test: ^1.21.0
